USE [master]
GO

/****** Object:  Database [DiscountCalculator]    Script Date: 08/01/2025 07:30:47 ******/
CREATE DATABASE [DiscountCalculator]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DiscountCalculator', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DiscountCalculator.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DiscountCalculator_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\DiscountCalculator_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DiscountCalculator].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DiscountCalculator] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DiscountCalculator] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DiscountCalculator] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DiscountCalculator] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DiscountCalculator] SET ARITHABORT OFF 
GO

ALTER DATABASE [DiscountCalculator] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DiscountCalculator] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DiscountCalculator] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DiscountCalculator] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DiscountCalculator] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DiscountCalculator] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DiscountCalculator] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DiscountCalculator] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DiscountCalculator] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DiscountCalculator] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DiscountCalculator] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DiscountCalculator] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DiscountCalculator] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DiscountCalculator] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DiscountCalculator] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DiscountCalculator] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DiscountCalculator] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DiscountCalculator] SET RECOVERY FULL 
GO

ALTER DATABASE [DiscountCalculator] SET  MULTI_USER 
GO

ALTER DATABASE [DiscountCalculator] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DiscountCalculator] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DiscountCalculator] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DiscountCalculator] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DiscountCalculator] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DiscountCalculator] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DiscountCalculator] SET QUERY_STORE = OFF
GO

ALTER DATABASE [DiscountCalculator] SET  READ_WRITE 
GO

